### ISSUE TITLE
how to ingest media

### ISSUE THREAD

**Issue by cooliobr** [nebulabroadcast/firefly#1]
Hi, im new on nebula, i need to add some media files, anyone can help me ?

**Comment by martastain** [comment]
Hello,
the easiest way is to set up a "watch" service, which basically just watches a folder for the new media files and creates new assets. This is described in the nebula-setup readme: https://github.com/nebulabroadcast/nebula-setup#watch . 
What is not (yet) documented is that you may also specify a script to be executed when an asset is created using a watchfolder. So if you for example want to add a GUID to each asset, you may use something like:

```xml
<service>
    <folder id_storage="1" path="media.dir" recursive="1" id_folder="1">
        <post><![CDATA[
import shortuuid
asset["id/main"] = shortuuid.uuid()
]]></post>
    </folder>
</service>
```

If you are using watchfolders, a media file (quite obviously) must exist prior to the creation of the asset.

Nebula also supports the opposite method: Create an asset first using the web interface or Firefly and enforce the user to fill all required metadata before they are able to upload the file. This can be done using an asset validation plugin: Create a file on your first storage `.nx/scripts/v5/validator/asset.py` and create a script similar to the following:

```python
class Plugin(ValidatorPlugin):
    def validate(self, asset):

        if not asset["title"]:
            # Return string with an error message in case metadata is incorrect
            return "Title is required"

        if len(asset["title"]) > 255:
            return "Title must be 255 characters or less"

        if not asset.id:
            # This is a new asset, so we save it first to get its ID
            asset.save() 

            # The file is expected in the media.dir directory and must be named by asset ID.
            path = "media.dir/{}.mxf".format(asset.id) 

            asset["id_storage"] = 1
            asset["path"] = path
            asset["content_type"] = VIDEO
            asset["media_type"] = FILE
        
        return asset
```

When the asset is created, Nebula expects the file at the specified location and after it's uploaded, it pairs automatically, metadata extraction is performed etc. This method is useful if you need to schedule clips for broadcasting before they are created: you just enter the expected duration during the asset creation and then use this offline asset in your rundown. When the file arrives, Nebula just marks the asset as online and updates the duration (as well as other technical metadata).

**Comment by cooliobr** [comment]
So, i do it, but do not understand how i can make a playlist.
some times ago i asked on nebula web site for a paid support/installation
but i don't received any reply
ANTIK Business Representative BRASIL
"Believe in the future, believe in your success"
"Não existe patch para a estupidez humana"





Em sex., 2 de out. de 2020 às 05:07, Martin Wacker <notifications@github.com>
escreveu:

**Comment by martastain** [comment]
Are you Rafael? If so, the last message I wrote to you contained system requirements for remote installation and a request for more information about your needs (Mar 2, 2020). I haven't received a reply. 

Both macro (block-based) and micro (item-based) scheduling for playback is described here:

https://nebulabroadcast.com/doc/nebula/scheduler.html
https://nebulabroadcast.com/doc/nebula/rundown.html

Keep in mind that assets must match conditions defined by `scheduler_accepts` and `rundown_accepts` values in the channel configuration.

**Comment by cooliobr** [comment]
Martin, what is cost to a full installation?
i have already CasparCG working with Intel QSV ( Linux ), i will need in
same machine, CasparCG and Nebula, all media files will in Samba share
location over /mnt/samba.



Att.

Rafael Machado
REGS IT LTDA.
ANTIK Business Representative BRASIL
"Believe in the future, believe in your success"
"Não existe patch para a estupidez humana"





Em sex., 2 de out. de 2020 às 12:46, Martin Wacker <notifications@github.com>
escreveu:

**Comment by martastain** [comment]
Send me an e-mail ( martin@nebulabroadcast.com ), please. This is outside of the scope of the Github issues page.

Thanks

Martin
